[package]
name = "lz77"
version = "0.1.1"
authors = ["Hongjie Zhai <zhaihj@live.jp>"]
description = "LZ77 compress/decompress in the Rust Programming Language"
repository = "https://github.com/zhaihj/lz77-rust"
readme = "README.md"
license = "MIT"

[dependencies]
